# Nicholas Locklear G01090642
# CS 262, Lab Section 221
# Lab 3

all: Lab3_nlocklea_221_Q1 Lab3_nlocklea_221_Q2 Lab3_nlocklea_221_Q3
problem1:
	gcc -g -Wall -o Lab3_Q1 Lab3_nlocklea_221_Q1.c
problem2:
	gcc -g -Wall -o Lab3_Q2 Lab3_nlocklea_221_Q2.c
problem3:
	gcc -g -Wall -o Lab3_Q3 Lab3_nlocklea_221_Q3.c
