/* DO NOT EDIT THIS FILE
 * - symtab.h (MUAN Calculator)
 * - Copyright: Prof. Kevin Andrea, George Mason University.  All Rights Reserved
 * - Date: Feb 2024
 */

#ifndef SYMTAB_H
#define SYMTAB_H

#include "tinysf.h"

void initialize_symtab();
int sym_exists(const char *name);
tinysf_s get_value(const char *name);
void insert_symbol(const char *name, tinysf_s value);
void teardown_symtab();

#endif
