
#Nicholas Locklear G01090642
#CS 262, Lab Section 221
#Lab 2

all: Lab2_nlocklea_221_Q1 Lab2_nlocklea_221_Q2 Lab2_nlocklea_221_Q3
problem1:
	gcc -Wall -o p1 Lab2_nlocklea_221_Q1.c
problem2:
	gcc -Wall -o p2 Lab2_nlocklea_221_Q2.c
problem3:
	gcc -Wall -o p3 Lab2_nlocklea_221_Q3.c
