# A simple Makefile
# Nicholas Locklear G01090642
# Cs262, 221
# Lab 2

CFLAGS=-g -Wall -std=c89 -pedantic-errors

LIBS=-lm

all: lab2_nlocklea_221.c
	gcc $(CFLAGS) -o lab2_nlocklea_221 lab2_nlocklea_221.c -lm

clean:
	rm lab2_nlocklea_221